/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an organisation and its owner user (FR-1.1, FR-1.2) */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive an access token (FR-1.1) */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current session — user + organisation */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employeeId}/salary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current pay — components + computed total (FR-3.1) */
        get: operations["SalaryController_current"];
        /** Edit salary with a required remark (FR-3.2, FR-3.3) */
        put: operations["SalaryController_edit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{employeeId}/salary/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salary-change history, newest first (FR-3.3) */
        get: operations["SalaryController_revisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/sample-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the pre-filled, importable template (FR-4.1) */
        get: operations["DataExchangeController_sampleSheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run import — buckets, nothing written (FR-4.1, FR-4.2) */
        post: operations["DataExchangeController_preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/import/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply import — insert new + confirmed overrides (FR-4.2) */
        post: operations["DataExchangeController_commit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the current filtered dataset, re-importable (FR-4.3) */
        get: operations["DataExchangeController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employees — paged/filtered/searched (FR-2.4) */
        get: operations["EmployeesController_list"];
        put?: never;
        /** Create an employee + initial salary in one tx (FR-2.1, FR-2.3) */
        post: operations["EmployeesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Employee detail incl. current salary summary */
        get: operations["EmployeesController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit core attributes — never salary (FR-2.1) */
        patch: operations["EmployeesController_update"];
        trace?: never;
    };
    "/api/v1/employees/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soft deactivate — status INACTIVE, history preserved (FR-2.1) */
        post: operations["EmployeesController_deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/{id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore status ACTIVE */
        post: operations["EmployeesController_reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Departments in this organisation */
        get: operations["ReferenceController_departments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/designations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Designations in this organisation */
        get: operations["ReferenceController_designations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global ISO countries */
        get: operations["ReferenceController_countries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Global ISO currencies */
        get: operations["ReferenceController_currencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headcount + per-currency total/average (FR-5.1) */
        get: operations["InsightsController_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-department, per-currency breakdown (FR-5.2) */
        get: operations["InsightsController_byDepartment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/by-country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-country, per-currency breakdown (FR-5.2) */
        get: operations["InsightsController_byCountry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignUpDto: {
            /** @example Priya Rao */
            name: string;
            /** @example priya@acme.com */
            email: string;
            /** @example s3cret-pass */
            password: string;
            /** @example ACME */
            organisationName: string;
        };
        UserDto: {
            /** @example usr_abc123 */
            id: string;
            /** @example Priya Rao */
            name: string;
            /** @example priya@acme.com */
            email: string;
        };
        OrganisationDto: {
            /** @example org_abc123 */
            id: string;
            /** @example ACME */
            name: string;
        };
        AuthResponseDto: {
            /**
             * @description Signed JWT bearer token
             * @example eyJhbGciOi…
             */
            accessToken: string;
            user: components["schemas"]["UserDto"];
            organisation: components["schemas"]["OrganisationDto"];
        };
        LogInDto: {
            /** @example priya@acme.com */
            email: string;
            /** @example s3cret-pass */
            password: string;
        };
        SessionResponseDto: {
            user: components["schemas"]["UserDto"];
            organisation: components["schemas"]["OrganisationDto"];
        };
        SalaryComponentDto: {
            /** @enum {string} */
            type: "BASIC" | "HOUSE_RENT_ALLOWANCE" | "SPECIAL_ALLOWANCE" | "TRANSPORT_ALLOWANCE" | "ANNUAL_BONUS";
            /** @description Annual amount in integer minor units (>= 0) */
            amountMinor: number;
        };
        SalaryViewDto: {
            employeeId: string;
            currency: string;
            components: components["schemas"]["SalaryComponentDto"][];
            totalMinor: number;
        };
        EditSalaryDto: {
            components: components["schemas"]["SalaryComponentDto"][];
            /** @description Reason for the change — required (FR-3.3) */
            remark: string;
        };
        ChangedByDto: {
            id: string;
            name: string;
        };
        RevisionViewDto: {
            id: string;
            oldTotalMinor: number | null;
            newTotalMinor: number;
            currency: string;
            remark: string;
            changedBy: components["schemas"]["ChangedByDto"];
            createdAt: string;
            componentsSnapshot: components["schemas"]["SalaryComponentDto"][];
        };
        RevisionPageDto: {
            data: components["schemas"]["RevisionViewDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        FieldChangeDto: {
            field: string;
            current: (string | number) | null;
            incoming: string | number;
            currency?: string;
        };
        ConflictRowDto: {
            rowNumber: number;
            employeeCode: string;
            changes: components["schemas"]["FieldChangeDto"][];
        };
        FailedRowDto: {
            rowNumber: number;
            employeeCode?: string;
            reasons: string[];
        };
        ImportPreviewResponseDto: {
            toInsert: number;
            conflicts: components["schemas"]["ConflictRowDto"][];
            invalid: components["schemas"]["FailedRowDto"][];
        };
        ImportReportResponseDto: {
            inserted: number;
            updated: number;
            skippedConflicts: number;
            failed: components["schemas"]["FailedRowDto"][];
        };
        EmployeeRowViewDto: {
            id: string;
            employeeCode: string;
            firstName: string;
            lastName: string;
            department: string;
            designation: string;
            country: string;
            currency: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            joinDate: string;
            salaryTotalMinor: number | null;
        };
        EmployeePageDto: {
            data: components["schemas"]["EmployeeRowViewDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        SalaryInputDto: {
            components: components["schemas"]["SalaryComponentDto"][];
        };
        CreateEmployeeDto: {
            /** @example EMP-1001 */
            employeeCode: string;
            /** @example Ravi */
            firstName: string;
            /** @example Kumar */
            lastName: string;
            departmentId: string;
            designationId: string;
            /**
             * @description ISO 3166-1 alpha-2
             * @example IN
             */
            countryCode: string;
            /**
             * @description ISO 4217
             * @example INR
             */
            currencyCode: string;
            /**
             * @description ISO date
             * @example 2021-04-01
             */
            joinDate: string;
            salary: components["schemas"]["SalaryInputDto"];
        };
        NamedReferenceDto: {
            id: string;
            name: string;
        };
        SalarySummaryViewDto: {
            currency: string;
            components: components["schemas"]["SalaryComponentDto"][];
            totalMinor: number;
        };
        EmployeeViewDto: {
            id: string;
            employeeCode: string;
            firstName: string;
            lastName: string;
            department: components["schemas"]["NamedReferenceDto"];
            designation: components["schemas"]["NamedReferenceDto"];
            countryCode: string;
            currencyCode: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE";
            joinDate: string;
            salary: components["schemas"]["SalarySummaryViewDto"] | null;
        };
        UpdateEmployeeDto: {
            /** @example EMP-1001 */
            employeeCode?: string;
            /** @example Ravi */
            firstName?: string;
            /** @example Kumar */
            lastName?: string;
            departmentId?: string;
            designationId?: string;
            /**
             * @description ISO 3166-1 alpha-2
             * @example IN
             */
            countryCode?: string;
            /**
             * @description ISO 4217
             * @example INR
             */
            currencyCode?: string;
            /**
             * @description ISO date
             * @example 2021-04-01
             */
            joinDate?: string;
        };
        ReferenceItemDto: {
            id: string;
            name: string;
        };
        CountryItemDto: {
            code: string;
            name: string;
        };
        CurrencyItemDto: {
            code: string;
            name: string;
            symbol: string;
            minorUnitDigits: number;
        };
        CurrencyGroupDto: {
            currency: string;
            headcount: number;
            totalMinor: number;
            averageMinor: number;
        };
        OverviewResponseDto: {
            headcount: number;
            byCurrency: components["schemas"]["CurrencyGroupDto"][];
        };
        BreakdownRowDto: {
            dimension: string;
            currencyGroups: components["schemas"]["CurrencyGroupDto"][];
        };
        BreakdownResponseDto: {
            breakdown: components["schemas"]["BreakdownRowDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
        };
    };
    SalaryController_current: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalaryViewDto"];
                };
            };
        };
    };
    SalaryController_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSalaryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalaryViewDto"];
                };
            };
        };
    };
    SalaryController_revisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employeeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPageDto"];
                };
            };
        };
    };
    DataExchangeController_sampleSheet: {
        parameters: {
            query?: {
                format?: "xlsx" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DataExchangeController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponseDto"];
                };
            };
        };
    };
    DataExchangeController_commit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description employeeCodes of the conflicts HR confirmed; omit/[] to insert new only */
                    applyEmployeeCodes?: string[];
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReportResponseDto"];
                };
            };
        };
    };
    DataExchangeController_export: {
        parameters: {
            query?: {
                format?: "xlsx" | "csv";
                /** @description field:dir — lastName|joinDate|salaryTotal */
                sort?: string;
                /** @description Case-insensitive match on name + employeeCode */
                search?: string;
                /** @description Filter by departmentId */
                department?: string;
                /** @description Filter by designationId */
                designation?: string;
                /** @description Filter by ISO country code */
                country?: string;
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EmployeesController_list: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: string;
                /** @description Rows per page (default 25, max 100) */
                pageSize?: string;
                /** @description field:dir — lastName|joinDate|salaryTotal */
                sort?: string;
                /** @description Case-insensitive match on name + employeeCode */
                search?: string;
                /** @description Filter by departmentId */
                department?: string;
                /** @description Filter by designationId */
                designation?: string;
                /** @description Filter by ISO country code */
                country?: string;
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeePageDto"];
                };
            };
        };
    };
    EmployeesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmployeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeViewDto"];
                };
            };
        };
    };
    EmployeesController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeViewDto"];
                };
            };
        };
    };
    EmployeesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmployeeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeViewDto"];
                };
            };
        };
    };
    EmployeesController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeViewDto"];
                };
            };
        };
    };
    EmployeesController_reactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeViewDto"];
                };
            };
        };
    };
    ReferenceController_departments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceItemDto"][];
                };
            };
        };
    };
    ReferenceController_designations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceItemDto"][];
                };
            };
        };
    };
    ReferenceController_countries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryItemDto"][];
                };
            };
        };
    };
    ReferenceController_currencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyItemDto"][];
                };
            };
        };
    };
    InsightsController_overview: {
        parameters: {
            query?: {
                /** @description Case-insensitive match on name / employee code */
                search?: string;
                /** @description Department id */
                department?: string;
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponseDto"];
                };
            };
        };
    };
    InsightsController_byDepartment: {
        parameters: {
            query?: {
                /** @description Case-insensitive match on name / employee code */
                search?: string;
                /** @description Department id */
                department?: string;
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponseDto"];
                };
            };
        };
    };
    InsightsController_byCountry: {
        parameters: {
            query?: {
                /** @description Case-insensitive match on name / employee code */
                search?: string;
                /** @description Department id */
                department?: string;
                /** @description ISO 3166-1 alpha-2 country code */
                country?: string;
                status?: "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponseDto"];
                };
            };
        };
    };
}
